
export interface User {
  id: string;
  name: string;
  role: string;
  avatar: string;
}

export enum EventType {
  TOUR = 'Tour',
  FESTIVAL = 'Festival',
  CONCERT = 'Concert',
  DAY_OFF = 'Day Off',
}

export enum EventStatus {
  ACTIVE = 'Active',
  PLANNING = 'Planning',
  COMPLETED = 'Completed',
}

export interface Event {
  id: string;
  title: string;
  dateRange: string;
  location: string;
  type: EventType;
  status: EventStatus;
  image: string;
  artist: string;
  logistics: {
    travel: number;
    hotel: number;
    tech: number;
  };
  readiness?: number;
  parent_id?: string;
  user_id?: string;
}

export interface TimelineItem {
  id: string;
  title: string;
  time: string;
  type: 'transport' | 'tech' | 'show' | 'hotel' | 'misc';
  status: 'pending' | 'active' | 'completed';
  isMajor?: boolean;
}

export interface Passenger {
  id: string;
  name: string;
  role: string;
  seat: string;
  ticketUrl?: string; // Simulated URL or filename
  status: 'Confirmed' | 'Pending' | 'Checked-In';
  avatar?: string;
}

export interface TransportItem {
  id: string;
  eventId?: string;
  type: 'flight' | 'train' | 'bus';
  provider: string;
  number: string;
  origin: string;
  destination: string;
  departureTime: string;
  arrivalTime: string;
  duration: string;
  status: 'On Time' | 'Delayed' | 'Scheduled';
  price?: string;
  passengers?: Passenger[];
}

export interface LodgingItem {
  id: string;
  eventId?: string;
  name: string;
  address: string;
  checkIn: string;
  checkInDate?: string;
  checkOut: string;
  checkOutDate?: string;
  stars: number;
  image: string;
  price?: string;
  rooms?: number;
  roomingList?: RoomingEntry[];
}

export interface RoomingEntry {
  id: string;
  room: string;
  guest: string;
  type: string;
  status: 'In House' | 'Pending' | 'Checked Out';
  floor: string;
}

export interface ScheduleItem {
  id: string;
  eventId?: string;
  startTime: string;
  endTime?: string;
  activity: string;
  location: string;
  type: 'logistics' | 'sound' | 'show' | 'hospitality' | 'other';
  notes?: string;
  isAutoGenerated?: boolean; // To distinguish from manual entries
  assignedTo?: string[]; // IDs of assigned contacts
  notify?: boolean;
  passengers?: Passenger[]; // For transport items containing passenger lists
}

export interface DocumentItem {
  id: string;
  eventId?: string;
  name: string;
  type: 'Technical' | 'Hospitality' | 'Other';
  size: string;
  version: string;
}

export interface Contact {
  id: string;
  name: string;
  role: string;
  email: string;
  phone: string;
  avatar: string;
  department?: string;
  team?: string; // New field for grouping
  city?: string;
  associatedVenue?: string;
  previousEvents?: string[];
  isTourCrew?: boolean;
  tourIds?: string[];
  eventIds?: string[]; // IDs of specific events (cities) this contact is assigned to
}

export interface Venue {
  id: string;
  name: string;
  city: string;
  country: string;
  address?: string;
  capacity: string;
  image: string;
  technicalRiderUrl?: string; // Simulated link
  contactName: string;
  contactEmail: string;
  contactPhone: string;
  notes?: string;
}

export interface NoteReply {
  id: string;
  author: string;
  avatar: string;
  content: string;
  date: string;
}

export interface Note {
  id: string;
  title: string;
  content: string;
  date: string;
  urgency: 'Normal' | 'Urgente' | 'Crítico';
  status: 'Open' | 'Done';
  associatedEventId?: string; // ID of the event
  taggedType: 'None' | 'Person' | 'Group';
  taggedId?: string; // ID of person or Name of Group
  pinned?: boolean;
  replies?: NoteReply[];
}