import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { TransportItem, LodgingItem, ScheduleItem, Contact, Venue, Note, NoteReply, Event, DocumentItem } from '../types';
import { supabase } from '../lib/supabase';
import { useAuth } from './AuthContext';

interface TourContextType {
  transportList: TransportItem[];
  lodgingList: LodgingItem[];
  manualSchedule: ScheduleItem[];
  contacts: Contact[];
  venues: Venue[];
  tourCrew: Contact[];
  notes: Note[];
  events: Event[];
  documents: DocumentItem[];
  addDocument: (doc: DocumentItem) => void;
  updateDocument: (doc: DocumentItem) => void;
  deleteDocument: (id: string) => void;
  createEvent: (event: Omit<Event, 'id'>) => Promise<Event | null>;
  updateEvent: (event: Event) => Promise<void>;
  deleteEvent: (id: string) => Promise<void>;
  addTransport: (item: TransportItem) => Promise<void>;
  updateTransport: (item: TransportItem) => Promise<void>;
  deleteTransport: (id: string) => Promise<void>;
  addLodging: (item: LodgingItem) => Promise<void>;
  updateLodging: (item: LodgingItem) => Promise<void>;
  deleteLodging: (id: string) => Promise<void>;
  addScheduleItem: (item: ScheduleItem) => Promise<void>;
  updateScheduleItem: (item: ScheduleItem) => Promise<void>;
  deleteScheduleItem: (id: string) => Promise<void>;
  addContact: (contact: Contact) => Promise<void>;
  updateContact: (contact: Contact) => Promise<void>;
  deleteContact: (id: string) => Promise<void>;
  addVenue: (venue: Venue) => Promise<void>;
  updateVenue: (venue: Venue) => Promise<void>;
  deleteVenue: (id: string) => Promise<void>;
  addTourCrew: (contact: Contact, tourId?: string) => Promise<void>;
  updateTourCrew: (contact: Contact) => Promise<void>;
  removeTourCrew: (id: string, tourId?: string) => Promise<void>;
  addNote: (note: Note) => Promise<void>;
  updateNote: (note: Note) => Promise<void>;
  deleteNote: (id: string) => Promise<void>;
  addNoteReply: (noteId: string, reply: NoteReply) => Promise<void>;
  addEventCrew: (contact: Contact, eventId: string) => Promise<void>;
  removeEventCrew: (contactId: string, eventId: string) => Promise<void>;
}

const TourContext = createContext<TourContextType | undefined>(undefined);

export const TourProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [transportList, setTransportList] = useState<TransportItem[]>([]);
  const [lodgingList, setLodgingList] = useState<LodgingItem[]>([]);
  const [manualSchedule, setManualSchedule] = useState<ScheduleItem[]>([]);
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [venues, setVenues] = useState<Venue[]>([]);
  const [notes, setNotes] = useState<Note[]>([]);
  const [events, setEvents] = useState<Event[]>([]);
  const [documents, setDocuments] = useState<DocumentItem[]>([]);

  // Local state for tour crew (subset of contacts)
  const [tourCrew, setTourCrew] = useState<Contact[]>([]);

  const { session } = useAuth();

  useEffect(() => {
    if (!session) return;

    const fetchData = async () => {
      // 1. Events
      const { data: eventsData } = await supabase.from('events').select('*');
      if (eventsData) {
        setEvents(eventsData.map((e: any) => ({
          ...e,
          dateRange: e.date_range,
        })));
      }

      // 2. Venues
      const { data: venuesData } = await supabase.from('venues').select('*');
      if (venuesData) {
        setVenues(venuesData.map((v: any) => ({
          ...v,
          contactName: v.contact_name,
          contactEmail: v.contact_email,
          contactPhone: v.contact_phone,
          technicalRiderUrl: v.technical_rider_url
        })));
      }

      // 3. Contacts
      const { data: contactsData } = await supabase.from('contacts').select('*');
      if (contactsData) {
        const mappedContacts = contactsData.map((c: any) => ({
          ...c,
          associatedVenue: c.associated_venue,
          previousEvents: c.previous_events,
          isTourCrew: c.is_tour_crew,
          tourIds: c.tour_ids || [],
          eventIds: c.event_ids || []
        }));
        setContacts(mappedContacts);
        setTourCrew(mappedContacts.filter((c: any) => c.isTourCrew));
      }

      // 4. Schedule
      const { data: scheduleData } = await supabase.from('schedule_items').select('*');
      if (scheduleData) {
        setManualSchedule(scheduleData.map((s: any) => ({
          ...s,
          eventId: s.event_id,
          startTime: s.start_time,
          endTime: s.end_time,
          isAutoGenerated: s.is_auto_generated,
          assignedTo: s.assigned_to
        })));
      }

      // 5. Transport
      const { data: transportData } = await supabase.from('transport_items').select('*');
      if (transportData) {
        setTransportList(transportData.map((t: any) => ({
          ...t,
          eventId: t.event_id,
          departureTime: t.departure_time,
          arrivalTime: t.arrival_time
        })));
      }

      // 6. Lodging
      const { data: lodgingData } = await supabase.from('lodging_items').select('*');
      if (lodgingData) {
        setLodgingList(lodgingData.map((l: any) => ({
          ...l,
          eventId: l.event_id,
          checkIn: l.check_in,
          checkOut: l.check_out,
          roomingList: l.rooming_list || []
        })));
      }

      // 7. Notes
      const { data: notesData } = await supabase.from('notes').select('*');
      if (notesData) {
        setNotes(notesData.map((n: any) => ({
          ...n,
          associatedEventId: n.associated_event_id,
          taggedType: n.tagged_type,
          taggedId: n.tagged_id
        })));
      }
    };

    fetchData();
  }, [session]);
  const createEvent = async (eventData: Omit<Event, 'id'>) => {
    const { title, dateRange, location, type, status, image, artist, logistics, parent_id, readiness } = eventData;
    const dbItem = {
      title,
      date_range: dateRange,
      location,
      type,
      status,
      image,
      artist,
      logistics,
      parent_id,
      readiness,
      user_id: session?.user?.id
    };

    const { data, error } = await supabase.from('events').insert([dbItem]).select().single();

    if (data && !error) {
      const newEvent: Event = {
        ...eventData,
        id: data.id,
        dateRange: data.date_range,
        parent_id: data.parent_id
      };
      setEvents(prev => [...prev, newEvent]);
      return newEvent;
    } else if (error) {
      console.error('Error creating event:', error);
      return null;
    }
    return null;
  };

  const updateEvent = async (event: Event) => {
    // Optimistic update
    setEvents(prev => prev.map(e => e.id === event.id ? event : e));

    const dbItem = {
      title: event.title,
      date_range: event.dateRange,
      location: event.location,
      type: event.type,
      status: event.status,
      image: event.image,
      artist: event.artist,
      logistics: event.logistics,
      readiness: event.readiness,
      parent_id: event.parent_id
    };
    const { error } = await supabase.from('events').update(dbItem).eq('id', event.id);

    if (error) {
      console.error('Error updating event:', error);
      // Rollback could be implemented here if strictly necessary
    }
  };

  const deleteEvent = async (id: string) => {
    const { error } = await supabase.from('events').delete().eq('id', id);
    if (!error) {
      setEvents(prev => prev.filter(e => e.id !== id));
    } else {
      console.error('Error deleting event:', error);
    }
  };


  const addTransport = async (item: TransportItem) => {
    // We treat the incoming item as having an ID, but usually it's temp. 
    // Ideally we omit ID for insert. Assuming item.id is temp or we ignore it.
    const { id, ...rest } = item;
    const dbItem = {
      event_id: rest.eventId,
      type: rest.type,
      provider: rest.provider,
      number: rest.number,
      origin: rest.origin,
      destination: rest.destination,
      departure_time: rest.departureTime,
      arrival_time: rest.arrivalTime,
      duration: rest.duration,
      status: rest.status,
      price: rest.price,
      passengers: rest.passengers
    };

    const { data, error } = await supabase.from('transport_items').insert([dbItem]).select().single();
    if (data && !error) {
      setTransportList(prev => [...prev, { ...item, id: data.id }]);
    }
  };

  const updateTransport = async (item: TransportItem) => {
    const dbItem = {
      event_id: item.eventId,
      type: item.type,
      provider: item.provider,
      number: item.number,
      origin: item.origin,
      destination: item.destination,
      departure_time: item.departureTime,
      arrival_time: item.arrivalTime,
      duration: item.duration,
      status: item.status,
      price: item.price,
      passengers: item.passengers
    };

    const { error } = await supabase.from('transport_items').update(dbItem).eq('id', item.id);
    if (!error) {
      setTransportList(prev => prev.map(t => t.id === item.id ? item : t));
    }
  };

  const deleteTransport = async (id: string) => {
    const { error } = await supabase.from('transport_items').delete().eq('id', id);
    if (!error) {
      setTransportList(prev => prev.filter(t => t.id !== id));
    }
  };

  const addLodging = async (item: LodgingItem) => {
    const { id, ...rest } = item;
    const dbItem = {
      name: rest.name,
      address: rest.address,
      check_in: rest.checkIn,
      check_out: rest.checkOut,
      stars: rest.stars,
      image: rest.image,
      price: rest.price,
      rooms: rest.rooms,
      rooming_list: rest.roomingList
    };

    const { data, error } = await supabase.from('lodging_items').insert([dbItem]).select().single();
    if (data && !error) {
      setLodgingList(prev => [...prev, { ...item, id: data.id }]);
    }
  };

  const updateLodging = async (item: LodgingItem) => {
    const dbItem = {
      event_id: item.eventId,
      name: item.name,
      address: item.address,
      check_in: item.checkIn,
      check_out: item.checkOut,
      stars: item.stars,
      image: item.image,
      price: item.price,
      rooms: item.rooms,
      rooming_list: item.roomingList
    };
    const { error } = await supabase.from('lodging_items').update(dbItem).eq('id', item.id);
    if (!error) {
      setLodgingList(prev => prev.map(l => l.id === item.id ? item : l));
    }
  };

  const deleteLodging = async (id: string) => {
    const { error } = await supabase.from('lodging_items').delete().eq('id', id);
    if (!error) {
      setLodgingList(prev => prev.filter(l => l.id !== id));
    }
  };

  const addScheduleItem = async (item: ScheduleItem) => {
    const { id, ...rest } = item;
    const dbItem = {
      event_id: rest.eventId,
      start_time: rest.startTime,
      end_time: rest.endTime,
      activity: rest.activity,
      location: rest.location,
      type: rest.type,
      notes: rest.notes,
      is_auto_generated: rest.isAutoGenerated,
      assigned_to: rest.assignedTo,
      notify: rest.notify
    };
    const { data, error } = await supabase.from('schedule_items').insert([dbItem]).select().single();
    if (data && !error) {
      setManualSchedule(prev => [...prev, { ...item, id: data.id }]);
    }
  };

  const updateScheduleItem = async (item: ScheduleItem) => {
    const dbItem = {
      event_id: item.eventId,
      start_time: item.startTime,
      end_time: item.endTime,
      activity: item.activity,
      location: item.location,
      type: item.type,
      notes: item.notes,
      is_auto_generated: item.isAutoGenerated,
      assigned_to: item.assignedTo,
      notify: item.notify
    };
    const { error } = await supabase.from('schedule_items').update(dbItem).eq('id', item.id);
    if (!error) {
      setManualSchedule(prev => prev.map(i => i.id === item.id ? item : i));
    }
  };

  const deleteScheduleItem = async (id: string) => {
    const { error } = await supabase.from('schedule_items').delete().eq('id', id);
    if (!error) {
      setManualSchedule(prev => prev.filter(i => i.id !== id));
    }
  };

  const addContact = async (contact: Contact) => {
    const { id, ...rest } = contact;
    const dbItem = {
      name: rest.name,
      role: rest.role,
      email: rest.email,
      phone: rest.phone,
      avatar: rest.avatar,
      department: rest.department,
      team: rest.team,
      city: rest.city,
      associated_venue: rest.associatedVenue,
      previous_events: rest.previousEvents,
      user_id: session?.user?.id
    };
    const { data, error } = await supabase.from('contacts').insert([dbItem]).select().single();
    if (data && !error) {
      setContacts(prev => [...prev, { ...contact, id: data.id }]);
    } else {
      console.error('Error adding contact:', error);
    }
  };

  const updateContact = async (contact: Contact) => {
    const dbItem = {
      name: contact.name,
      role: contact.role,
      email: contact.email,
      phone: contact.phone,
      avatar: contact.avatar,
      department: contact.department,
      team: contact.team,
      city: contact.city,
      associated_venue: contact.associatedVenue,
      previous_events: contact.previousEvents
    };
    const { error } = await supabase.from('contacts').update(dbItem).eq('id', contact.id);
    if (!error) {
      setContacts(prev => prev.map(c => c.id === contact.id ? contact : c));
    }
  };

  const deleteContact = async (id: string) => {
    const { error } = await supabase.from('contacts').delete().eq('id', id);
    if (!error) {
      setContacts(prev => prev.filter(c => c.id !== id));
    }
  };

  const addVenue = async (venue: Venue) => {
    const { id, ...rest } = venue;
    const dbItem = {
      name: rest.name,
      city: rest.city,
      country: rest.country,
      address: rest.address,
      capacity: rest.capacity,
      image: rest.image,
      technical_rider_url: rest.technicalRiderUrl,
      contact_name: rest.contactName,
      contact_email: rest.contactEmail,
      contact_phone: rest.contactPhone,
      notes: rest.notes
    };
    const { data, error } = await supabase.from('venues').insert([dbItem]).select().single();
    if (data && !error) {
      setVenues(prev => [...prev, { ...venue, id: data.id }]);
    }
  };

  const updateVenue = async (venue: Venue) => {
    const dbItem = {
      name: venue.name,
      city: venue.city,
      country: venue.country,
      address: venue.address,
      capacity: venue.capacity,
      image: venue.image,
      technical_rider_url: venue.technicalRiderUrl,
      contact_name: venue.contactName,
      contact_email: venue.contactEmail,
      contact_phone: venue.contactPhone,
      notes: venue.notes
    };
    const { error } = await supabase.from('venues').update(dbItem).eq('id', venue.id);
    if (!error) {
      setVenues(prev => prev.map(v => v.id === venue.id ? venue : v));
    }
  };

  const deleteVenue = async (id: string) => {
    const { error } = await supabase.from('venues').delete().eq('id', id);
    if (!error) {
      setVenues(prev => prev.filter(v => v.id !== id));
    }
  };

  const addTourCrew = async (contact: Contact, tourId?: string) => {
    // Logic:
    // 1. If contact exists, update their tour_ids (and is_tour_crew).
    // 2. If new, create with tour_ids.

    const existingContact = contacts.find(c => c.id === contact.id);

    if (existingContact) {
      const currentTourIds = existingContact.tourIds || [];
      // valid tourId and not already present
      const newTourIds = (tourId && !currentTourIds.includes(tourId))
        ? [...currentTourIds, tourId]
        : currentTourIds;

      const updates: any = { is_tour_crew: true };
      if (tourId) updates.tour_ids = newTourIds;

      const { error } = await supabase.from('contacts').update(updates).eq('id', contact.id);

      if (!error) {
        const updatedContact = { ...existingContact, isTourCrew: true, tourIds: newTourIds };
        // Update local state
        setContacts(prev => prev.map(c => c.id === contact.id ? updatedContact : c));
        // Update tourCrew (global list) - currently we just add if not present
        if (!tourCrew.find(c => c.id === contact.id)) {
          setTourCrew(prev => [...prev, updatedContact]);
        } else {
          setTourCrew(prev => prev.map(c => c.id === contact.id ? updatedContact : c));
        }
      }
    } else {
      // Create new contact
      const { id, ...rest } = contact;
      const initialTourIds = tourId ? [tourId] : [];

      const dbItem = {
        name: rest.name,
        role: rest.role,
        email: rest.email,
        phone: rest.phone,
        avatar: rest.avatar,
        department: rest.department,
        team: rest.team,
        city: rest.city,
        associated_venue: rest.associatedVenue,
        previous_events: rest.previousEvents,
        is_tour_crew: true,
        tour_ids: initialTourIds,
        user_id: session?.user?.id
      };

      const { data, error } = await supabase.from('contacts').insert([dbItem]).select().single();
      if (data && !error) {
        const newContact = { ...contact, id: data.id, isTourCrew: true, tourIds: initialTourIds };
        setContacts(prev => [...prev, newContact]);
        setTourCrew(prev => [...prev, newContact]);
      } else {
        console.error('Error adding tour crew:', error);
      }
    }
  };

  const updateTourCrew = async (contact: Contact) => {
    // Just update the contact details
    await updateContact(contact);
    setTourCrew(prev => prev.map(c => c.id === contact.id ? contact : c));
  };

  const removeTourCrew = async (id: string, tourId?: string) => {
    const contact = contacts.find(c => c.id === id);
    if (!contact) return;

    if (tourId) {
      // Remove specific tourId
      const newTourIds = (contact.tourIds || []).filter(tid => tid !== tourId);
      // If no more tours, maybe set is_tour_crew = false? 
      // For now, let's keep is_tour_crew = true unless explicitly unset, OR sync it.
      // Let's sync it: if newTourIds.length === 0, set is_tour_crew = false.
      const isStillCrew = newTourIds.length > 0;

      const { error } = await supabase.from('contacts').update({
        tour_ids: newTourIds,
        is_tour_crew: isStillCrew
      }).eq('id', id);

      if (!error) {
        const updatedContact = { ...contact, tourIds: newTourIds, isTourCrew: isStillCrew };
        setContacts(prev => prev.map(c => c.id === id ? updatedContact : c));
        if (!isStillCrew) {
          setTourCrew(prev => prev.filter(c => c.id !== id));
        } else {
          setTourCrew(prev => prev.map(c => c.id === id ? updatedContact : c));
        }
      }
    } else {
      // Legacy behavior: remove completely from global tour crew
      const { error } = await supabase.from('contacts').update({ is_tour_crew: false }).eq('id', id);
      if (!error) {
        setTourCrew(prev => prev.filter(c => c.id !== id));
        setContacts(prev => prev.map(c => c.id === id ? { ...c, isTourCrew: false } : c));
      }
    }
  };

  const addEventCrew = async (contact: Contact, eventId: string) => {
    const existingContact = contacts.find(c => c.id === contact.id);

    if (existingContact) {
      const currentEventIds = existingContact.eventIds || [];
      // valid eventId and not already present
      const newEventIds = (!currentEventIds.includes(eventId))
        ? [...currentEventIds, eventId]
        : currentEventIds;

      const { error } = await supabase.from('contacts').update({ event_ids: newEventIds }).eq('id', contact.id);

      if (error) console.error("addEventCrew error:", error);
      if (!error) {
        const updatedContact = { ...existingContact, eventIds: newEventIds };
        setContacts(prev => prev.map(c => c.id === contact.id ? updatedContact : c));
        // Also update tourCrew if this contact is in it
        setTourCrew(prev => prev.map(c => c.id === contact.id ? updatedContact : c));
      }
    } else {
      // Logic for new contact adding directly to event (less common, usually search exists)
      console.warn("addEventCrew called with non-existent contact (not implemented yet)");
    }
  };

  const removeEventCrew = async (contactId: string, eventId: string) => {
    const contact = contacts.find(c => c.id === contactId);
    if (!contact) return;

    const newEventIds = (contact.eventIds || []).filter(eid => eid !== eventId);

    const { error } = await supabase.from('contacts').update({ event_ids: newEventIds }).eq('id', contactId);

    if (!error) {
      const updatedContact = { ...contact, eventIds: newEventIds };
      setContacts(prev => prev.map(c => c.id === contactId ? updatedContact : c));
      setTourCrew(prev => prev.map(c => c.id === contactId ? updatedContact : c));
    }
  };

  const addNote = async (note: Note) => {
    const { id, ...rest } = note;
    const dbItem = {
      title: rest.title,
      content: rest.content,
      date: rest.date,
      urgency: rest.urgency,
      status: rest.status,
      associated_event_id: rest.associatedEventId,
      tagged_type: rest.taggedType,
      tagged_id: rest.taggedId,
      pinned: rest.pinned,
      replies: rest.replies
    };
    const { data, error } = await supabase.from('notes').insert([dbItem]).select().single();
    if (data && !error) {
      setNotes(prev => [{ ...note, id: data.id }, ...prev]);
    }
  };

  const updateNote = async (note: Note) => {
    const dbItem = {
      title: note.title,
      content: note.content,
      date: note.date,
      urgency: note.urgency,
      status: note.status,
      associated_event_id: note.associatedEventId,
      tagged_type: note.taggedType,
      tagged_id: note.taggedId,
      pinned: note.pinned,
      replies: note.replies
    };
    const { error } = await supabase.from('notes').update(dbItem).eq('id', note.id);
    if (!error) {
      setNotes(prev => prev.map(n => n.id === note.id ? note : n));
    }
  };

  const deleteNote = async (id: string) => {
    const { error } = await supabase.from('notes').delete().eq('id', id);
    if (!error) {
      setNotes(prev => prev.filter(n => n.id !== id));
    }
  };

  const addDocument = (doc: DocumentItem) => {
    setDocuments(prev => [...prev, doc]);
  };

  const updateDocument = (doc: DocumentItem) => {
    setDocuments(prev => prev.map(d => d.id === doc.id ? doc : d));
  };

  const deleteDocument = (id: string) => {
    setDocuments(prev => prev.filter(d => d.id !== id));
  };

  const addNoteReply = async (noteId: string, reply: NoteReply) => {
    // First get existing replies
    const note = notes.find(n => n.id === noteId);
    if (!note) return;

    const newReplies = [...(note.replies || []), reply];

    const { error } = await supabase.from('notes').update({ replies: newReplies }).eq('id', noteId);

    if (!error) {
      setNotes(prev => prev.map(n => {
        if (n.id === noteId) {
          return { ...n, replies: newReplies };
        }
        return n;
      }));
    }
  };


  return (
    <TourContext.Provider value={{
      transportList,
      lodgingList,
      manualSchedule,
      contacts,
      venues,
      tourCrew,
      notes,
      events,
      createEvent,
      updateEvent,
      deleteEvent,
      addTransport,
      updateTransport,
      addLodging,
      addScheduleItem,
      updateScheduleItem,
      deleteScheduleItem,
      addContact,
      updateContact,
      deleteContact,
      addVenue,
      updateVenue,
      deleteVenue,
      addTourCrew,
      updateTourCrew,
      removeTourCrew,
      deleteTransport,
      updateLodging,
      deleteLodging,
      addNote,
      updateNote,
      deleteNote,
      addNoteReply,
      documents,
      addDocument,
      updateDocument,
      deleteDocument,
      addEventCrew,
      removeEventCrew
    }}>
      {children}
    </TourContext.Provider>
  );
};

export const useTour = () => {
  const context = useContext(TourContext);
  if (context === undefined) {
    throw new Error('useTour must be used within a TourProvider');
  }
  return context;
};